Add Java section, and update README
xebia-functional/xef pull request #248
Opened 2023-07-17 14:46 UTC by nomisRev

2023-07-17 14:52 UTC, Yawolf submitted a review, later dismissed

2023-07-17 15:16 UTC, anamariamv approved these changes
Minor typo

2023-07-17 15:16 UTC, anamariamv commented on README.md
> +- [<img src="https://en.wikipedia.org/wiki/Java_(programming_language)#/media/File:Java_programming_language_logo.svg" height="15px" alt="Scala logo"> Examples in Java](https://github.com/xebia-funct
```suggestion
- [<img src="https://en.wikipedia.org/wiki/Java_(programming_language)#/media/File:Java_programming_language_logo.svg" height="15px" alt="Java logo"> Examples in Java](https://github.com/xebia-functional/xef/tree/main/examples/java/src/main/java/com/xebia/functional/xef/java/auto)
```

2023-07-17 15:16 UTC, anamariamv commented on README.md
> +- [<img src="https://en.wikipedia.org/wiki/Java_(programming_language)#/media/File:Java_programming_language_logo.svg" height="15px" alt="Scala logo"> Java version](https://github.com/xebia-functiona
```suggestion
- [<img src="https://en.wikipedia.org/wiki/Java_(programming_language)#/media/File:Java_programming_language_logo.svg" height="15px" alt="Java logo"> Java version](https://github.com/xebia-functional/xef/blob/main/docs/intro/java.md)
```

2023-07-18 05:06 UTC, juanpedromoreno requested changes
Thanks @nomisRev , I think we need to remove the `xef-core` dependency from the docs everywhere.

2023-07-18 05:06 UTC, juanpedromoreno commented on README.md
> +   <artifactId>xef-core</artifactId>
```suggestion
   <artifactId>xef-java</artifactId>
```

2023-07-18 07:10 UTC, nomisRev commented
You're absolutely right @juanpedromoreno. I removed all references to `xef-core` from the documentation with exception of the badges.

2023-07-18 08:56 UTC, juanpedromoreno approved these changes
🙌

2023-07-18 09:47 UTC, merged